apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: myapp
      labels:
        app: nginx
        ver: "1.0"
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
